# Generated by Django 3.0 on 2021-07-02 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('idActividad', models.AutoField(primary_key=True, serialize=False)),
                ('actividad', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('idArea', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Areas',
                'ordering': ['area'],
            },
        ),
        migrations.CreateModel(
            name='Estatus_actividad',
            fields=[
                ('idEstatusActividad', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Estatus_actividades',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('idSector', models.AutoField(primary_key=True, serialize=False)),
                ('sector', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Sectores',
            },
        ),
        migrations.CreateModel(
            name='Tipo_area',
            fields=[
                ('idTipoArea', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_area', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tipo_areas',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('idTurno', models.AutoField(primary_key=True, serialize=False)),
                ('turno', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.CreateModel(
            name='Usuario_activo',
            fields=[
                ('idUsuarioActivo', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Usuarios_activos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=60)),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroActividad.Area')),
                ('id_tipo_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroActividad.Tipo_area')),
                ('id_usuario_activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroActividad.Usuario_activo')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Registro_actividad',
            fields=[
                ('idRegistroActividad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fechaRegistro', models.DateField(auto_now=True, verbose_name='Fecha')),
                ('idActividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroActividad.Actividad', verbose_name='Actividad')),
                ('idEstatusActividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroActividad.Estatus_actividad', verbose_name='Estatus')),
                ('idTurno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroActividad.Turno', verbose_name='Turno')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroActividad.Usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Registro_actividades',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='idTipoArea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroActividad.Tipo_area'),
        ),
    ]
